name: Latest toot from Mastodon

on:
  schedule:
    - cron: "0 */12 * * *" # Every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-mastodon:
    name: Update this repo's README with latest Mastodon toot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in latest toot
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://techhub.social/@mmornati.rss"
          comment_tag_name: "MASTODON-LATEST"
          template: "💬 $description $newline $newline — [view on Mastodon]($url)"
          max_post_count: 1
          commit_message: "chore: update latest toot from Mastodon"
          disable_html_encoding: "true"
          description_max_length: "350"
          tag_post_pre_newline: "true"
          custom_tags: "description, link"
