name: Generate Streak Stats

on:
  schedule:
    - cron: "0 3 * * *" # 03:00 UTC = 05:00 Paris
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/streak-stats.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@v1.7.0
        with:
          options: user=mmornati&theme=tokyonight&hide_border=true&locale=fr
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: crazy-max/ghaction-github-pages@v5.0.0
        with:
          target_branch: output
          build_dir: profile
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
